export const ROOT = 'products';

export const FETCH_PRODUCTS_REQUEST  = `${ROOT}/FETCH_PRODUCTS_REQUEST`;
export const FETCH_PRODUCTS_FAILURE = `${ROOT}/FETCH_PRODUCTS_FAILURE`;
export const FETCH_PRODUCTS_SUCCESS = `${ROOT}/FETCH_PRODUCTS_SUCCESS`;